[package]
name = "powermate-volume"
version = "0.1.0"
edition = "2024"
description = "Use a Griffin PowerMate as a volume knob and media controller on modern Windows"
license = "MIT"
repository = "https://github.com/pwicks86/powermate-volume"

[dependencies]
futures-lite = "2.6.1"
anyhow = "1.0.102"
hidapi = "2.6.5"
windows = { version = "0.62.2", features = [
    "Win32_Media_Audio",
    "Win32_System_Com",
    "Win32_System_Variant",
    "Win32_Media_Audio_Endpoints",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant",
    "Win32_System_Diagnostics",
    "Win32_System_Diagnostics_Debug",
    "Win32_UI_Input_KeyboardAndMouse",

] }
log = "0.4.29"
tray-icon = "0.22.1"
winit = "0.30.13"
image = { version = "0.25.10", default-features = false, features = ["png"] }
tokio = {
   version= "1.52.1",
   features = ["rt-multi-thread", "macros", "time", "sync"] 
}
clap = { version = "4.6.1", features = ["derive"] }
winreg = "0.56.0"

[build-dependencies]
image = { version = "0.25.10", default-features = false, features = ["png", "ico"] }
winresource = "0.1.31"
